basePath: /api
definitions:
  controller.ArticleSwag:
    properties:
      body:
        type: string
      createdAt:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      userName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: go-clean-architecture
  title: go-clean-architecture
  version: 0.0.1
paths:
  /api/article:
    delete:
      consumes:
      - application/json
      description: Article 을 제거합니다.
      operationId: delete-article
      parameters:
      - description: 삭제할 Article 제목
        in: path
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Article 제거
      tags:
      - Article
    post:
      consumes:
      - application/json
      description: Article 을 생성합니다.
      operationId: create-article
      parameters:
      - description: 새로운 Article 정보
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/controller.ArticleSwag'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ArticleSwag'
      summary: Article 생성
      tags:
      - Article
  /api/article/{title}:
    get:
      description: 단일 Article 을 조회합니다.
      operationId: get-article
      parameters:
      - description: 조회할 Article 제목
        in: path
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ArticleSwag'
      summary: 단일 Article 조회
      tags:
      - Article
  /api/articles:
    get:
      description: Article 리스트를 조회합니다.
      operationId: get-articles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.ArticleSwag'
            type: array
      summary: Article 리스트 조회
      tags:
      - Article
swagger: "2.0"
